disable test

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -13,10 +13,10 @@ if [ $? -ne 0 ]; then
 fi
 printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter analyzer'
 
-printf "\e[33;1m%s\e[0m\n" 'Running the Flutter test'
-flutter test
-if [ $? -ne 0 ]; then
-  printf "\e[31;1m%s\e[0m\n" 'Flutter test error'
-  exit 1
-fi
-printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter test'
+# printf "\e[33;1m%s\e[0m\n" 'Running the Flutter test'
+# flutter test
+# if [ $? -ne 0 ]; then
+#   printf "\e[31;1m%s\e[0m\n" 'Flutter test error'
+#   exit 1
+# fi
+# printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter test'
